project:
  type: book
  output-dir: docs

lang: ja

book:
  title: "プレゼミ講義ノート"
  reader-mode: true
  author:
    - name: "Soichi Matsuura"
    - affiliation: Ritsumeikan University
    - email: matsuura@fc.ritsumei.ac.jp
  favicon: img/favicon.ico

  site-url: https://so-ichi.com
  repo-url: https://github.com/ma2ura/presemi/
  repo-branch: main
  twitter-card: true

  chapters:
    - index.qmd
    - presemi2023_01.qmd
    - presemi2023_02.qmd
    - presemi2023_03.qmd
    - presemi2023_04.qmd
    - presemi2023_05.qmd
    - presemi2023_06.qmd
    - presemi2023_07.qmd
    - presemi2023_08.qmd
    - presemi2023_09.qmd
    - presemi2023_10.qmd
    # - presemi2023_11.qmd


  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    background: "#a10000"
    left: "Copyright 2026, Soichi Matsuura"
    right:
      - icon: github
        href: https://github.com/ma2ura/presemi/
      - icon: twitter
        href: https://twitter.com/matsuura_rits
        aria-label: Twitter

format:
  epub:
    title: プレゼミ講義ノート
    subtitle: 2023年度秋学期
    date: "2023年8月16日改訂"
    author: 松浦総一
    toc: true
    html-math-method: katex

  html:
    theme:
      light:
       - cerulean
      #  - theme.scss
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    link-external-icon: true
    df-print: kable
    grid:
      sidebar-width: 200px
      body-width: 1200px
    css:
      - "mystyle.css"
execute:
  message: false
  warning: false
  fig-width: 14
  fig-height: 8

# knitr:
#   opts_chunk:
#     dev: cairo_pdf
monofontoptions:
  - Scale = .6

knitr:
  opts_chunk:
    dev: "ragg_png"
    dpi: 600
