project:
  type: website
  output-dir: docs

lang: ja

website:
  title: "プレゼミ講義ノート"
  navbar:
    left:
      - text: "講義内容"
      - menu:
        - text: "はじめに"
          file: index.qmd
        - text: "第1回 講義ガイダンス"
          file: presemi2023_01.qmd
        - text: "第2回 実証研究"
          file: presemi2023_02.qmd
        - text: "第3回 Rの使い方"
          file: presemi2023_03.qmd
        - text: "第4回 Rによるデータ操作"
          file: presemi2023_04.qmd
        - text: "第5回 記述統計と可視化"
          file: presemi2023_05.qmd
        - text: "第6回 統計的推定"
          file: presemi2023_06.qmd
        - text: "第7回 統計的仮説検定"
          file: presemi2023_07.qmd
        - text: "第8回 変数間の関連性"
          file: presemi2023_08.qmd
        - text: "第9回 回帰分析の基礎"
          file: presemi2023_09.qmd

  page-navigation: true

  page-footer:
    border: true
    left: "Copyright 2023, Soichi Matsuura"
    right:
      - icon: github
        href: https://github.com/ma2ura
      - icon: twitter
        href: https://twitter.com/matsuura_rits
        aria-label: Twitter

  favicon: favicon.ico


format:
  html:
    theme:
      light:
       - cerulean
       - theme.scss
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    link-external-icon: true
    df-print: kable
    grid:
      sidebar-width: 200px
      body-width: 1200px

execute:
  message : false
  warning: false
  fig-width: 14
  fig-height: 8
  freeze: auto
  cache: refresh

# knitr:
#   opts_chunk:
#     dev: cairo_pdf
monofontoptions:
  - Scale = .6


