project:
  type: book
  output-dir: docs

book:
  title: "プレゼミ講義ノート"
  subtitle : "2023年度秋学期"
  author: "Soichi Matsuura"
  date: "7/3/2023"
  reader-mode: true
  language: "ja"
  sidebar:
    alignment: left
    style: "docked"
    search: true

  navbar:
    search: true
    background: "#a10000"
    logo: "img/rits_logo.pdf"
    left:
      - text: "はじめに"
        file: index.qmd
      - text: "第1回 講義ガイダンス"
        file: presemi2023_01.qmd
      - text: "第2回 実証研究"
        file: presemi2023_02.qmd
      - text: "第3回 Rの使い方"
        file: presemi2023_03.qmd
      - text: "第4回 Rによるデータ操作"
        file: presemi2023_04.qmd
      # - text: "第5回 記述統計と可視化"
      #   file: presemi2023_05.qmd
      # - text: "第6回 統計的推定"
      #   file: presemi2023_06.qmd
      # - text: "第7回 統計的仮説検定"
      #   file: presemi2023_07.qmd
      # - text: "第8回 変数間の関連性"
      #   file: presemi2023_08.qmd
      # - text: "第9回 回帰分析の基礎"
      #   file: presemi2023_09.qmd
      # - text: "第10回 回帰分析の統計的推定"
      #   file: presemi2023_10.qmd
      # - text: "第11回 ロジスティック回帰分析"
      #   file: presemi2023_11.qmd
    right:
      - icon: house
        href: https://so-ichi.com
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/matsuura_rits
        aria-label: Twitter
  page-footer:
    left: |
      プレゼミ講義ノート
    right: |
      本書は <a href="https://quarto.org/">Quarto</a> で作成されました。
  # cover-image: "img/empirical_politics.jpg"
  cover-image: "img/rits_logo.png"
  favicon: favicon.ico

  chapters:
    - index.qmd
    - presemi2023_01.qmd
    - presemi2023_02.qmd
    - presemi2023_03.qmd
    - presemi2023_04.qmd
    # - presemi2023_05.qmd
    # - presemi2023_06.qmd
    # - presemi2023_07.qmd
    # - presemi2023_08.qmd
    # - presemi2023_09.qmd
    # - presemi2023_10.qmd
    # - presemi2023_11.qmd
    # - presemi2023_12.qmd
    # - presemi2023_13.qmd
    # - presemi2023_14.qmd
    # - presemi2023_15.qmd
    # - presemi2023_final.qmd
format:
  epub:
    title: プレゼミ講義ノート
    subtitle: 2023年度秋学期
    date: "2023年8月16日改訂"
    author: 松浦総一
    toc: true
    html-math-method: katex
  html:
    theme: cosmo
    html-math-method: katex
    grid:
      sidebar-width: 200px
      body-width: 1200px
  pdf:
    pdf-engine: lualatex
    toc: true
    number-sections: true
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{luatexja}
          \usepackage{float}
          \usepackage{xcolor}
          \usepackage{tabularx}
          \usepackage{amsmath}
          \usepackage{engrec}
          \usepackage{fontspec}


code-block-bg: "#F6F6F6"

execute:
  message : false
  warning: false
  fig-width: 14
  fig-height: 8

knitr:
  opts_chunk:
    dev: cairo_pdf
monofontoptions:
  - Scale=.6


