{
  "hash": "e0f11d29c73e51fd3493abe5e52099d8",
  "result": {
    "markdown": "# 変数間の関連性\n\n第8回講義の**到達目標**は、\n\n- カテゴリー変数間の関連性を調べる方法を学ぶ。\n- 2変数の関係を表す統計量を出力できる。\n- 統計量から結果を解釈し，意味のある主張をすることができる。\n-\n第8回講義の**到達度検証のための課題**は、以下の通りです。\n\n- カテゴリー変数間の関連性を調べる方法を説明できる。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-1_74e8aaa052da5f073a99ef9c1f908389'}\n\n:::\n\n\nこの章では、2つ以上の変数間の関係を調べる方法を学びます。\n1つめは、カテゴリー変数間の関係を調べる方法として、クロス集計表とカイ二乗検定を学びます。\n2つめは、量的変数間の関係を調べる方法として、相関係数と散布図を学びます。\n\n## カテゴリー変数の関連\n\n### クロス集計表\n\nカテゴリー変数は、その値がどのカテゴリーに属するかということを表す変数です。\n2つのカテゴリー変数の関連性を調べるためにはクロス集計表を作ることが有益です。\n例えば、40名のクラスに、男が25名、女が15名います。\nまた、クラスの中で、メガネをかけている男が4名、メガネを掛けている女が8名いました。\nこのクロス集計表は次のようなものになります。\n\n|  | メガネをかけている | メガネをかけていない | 合計 |\n|:--:|:--:|:--:|:--:|\n| 男 | 41 | 204 | 245 |\n| 女 | 81 | 74 | 155 |\n| 合計 | 122 | 278 | 400 |\n\n\n\nこの表から、メガネをかけている人の割合は、男性の中で$41 \\div 204 =\"0.2009804、女性の中で$81 \\div 155 = $0.52であることから、女子学生の方がメガネをかける傾向にあることが分かりました。\n\n\n### カイ二乗検定\n\nこのクロス集計表から読み取れる関係が、統計的に意味があるのかどうかを調べるためには、$\\chi ^2$(カイ二乗)検定を行います。\n$\\chi^2$検定は次のステップで実行します。\n\n1. 帰無仮説として、カテゴリー変数間に**関連性はない**と仮定\n2. その仮定のもとで、観測されたクロス集計表の度数が、**理論的に予測される度数と大きく異なるかどうか**を検定\n3. 予測される度数と観測された度数の差が大きいほど、帰無仮説が棄却される\n\n$\\chi^2$検定で用いられる統計量は、$\\chi^2$統計量と呼ばれ、次の式で計算されます。\n\n$$\n\\chi^2 = \\sum_{i=1}^n \\sum_{j=1}^m \\frac{(O_{ij} - E_{ij})^2}{E_{ij}}\n$$\nここで、$O_{ij}$は観測された度数(観測度数)、$E_{ij}$は理論的に予測される度数(期待度数)です。$n$と$m$はカテゴリー変数のカテゴリー数です。\nつまり、2つのカテゴリー変数の関連性を調べる場合、$\\chi^2$統計量は次のように計算されます。\n\n$$\n\\begin{aligned}\n\\chi^2 &= \\frac{(O_{11} - E_{11})^2}{E_{11}} + \\frac{(O_{12} - E_{12})^2}{E_{12}} \\\\\n&+ \\frac{(O_{21} - E_{21})^2}{E_{21}} + \\frac{(O_{22} - E_{22})^2}{E_{22}}\n\\end{aligned}\n$$\n\nここで、期待度数$E$をどうやって求めるのか、が問題となります。\n期待度数の「期待」の意味は、帰無仮説のもとで期待される度数です。\n\n$$\nE_{ij} = \\frac{O_{i\\cdot} \\times O_{\\cdot j}}{O_{\\cdot \\cdot}}\n$$\nここで、$O_{i\\cdot}$は$i$行目の合計(横の合計)、$O_{\\cdot j}$は$j$列目の合計(縦の合計)、$O_{\\cdot \\cdot}$は全体の合計です。\n\n先のメガネの例で計算してみます。\n観察度数$O$は次のようになります。\n\n|  | メガネをかけている | メガネをかけていない | 合計 |\n|:--:|:--:|:--:|:--:|\n| 男 | 41 | 204 | 245 |\n| 女 | 81 | 74 | 155 |\n| 合計 | 122 | 278 | 400 |\n\n\n\n男の行合計$O_{男\\cdot}$は245、女の行合計$O_{女\\cdot}$は155、メガネ有りの列合計$O_{\\cdot メガネ有}$は122、メガネなしの列合計$O_{\\cdot メガネ無}$は278、全体の合計$O_{\\cdot \\cdot}$は400となります。\nここから、期待度数は次のように計算されます。\n\n$$\n\\begin{aligned}\nE_{男, メガネ} &= \\frac{245 \\times 122}{400} = 74.725 \\\\\nE_{男, メガネ無} &= \\frac{245 \\times 278}{400} = 170.275 \\\\\nE_{女, メガネ} &= \\frac{155 \\times 122}{400} = 47.275 \\\\\nE_{女, メガネ無} &= \\frac{155 \\times 278}{400} = 107.725\n\\end{aligned}\n$$\n\n\nよって期待度数$E$は次のようになります。\n\n|  | メガネをかけている | メガネをかけていない | 合計 |\n|:--:|:--:|:--:|:--:|\n| 男 | 74.725 | 170.275 | 245 |\n| 女 | 47.275 | 107.725 | 155 |\n| 合計 | 122 | 278 | 400 |\n\nここから、定義通りに、$\\chi^2$統計量を計算します。\n\n$$\n\\begin{aligned}\n\\chi^2 = \\frac{(41 - 74.725)^2}{74.725} + \\frac{(204 - 170.275)^2}{170.275} + \\frac{(81 - 47.275)^2}{47.275} + \\frac{(74 - 107.725)^2}{107.725} = 7.2\n\\end{aligned}\n$$\n\n\nここで計算した$\\chi^2$統計量は、自由度1の$\\chi^2$分布に従うということが知られています。この自由度は、カテゴリー変数のカテゴリー数から1を引いたものです。\nここでは、2カテゴリー同士のクロス集計表なので、自由度は$(2-1) \\times (2-1) = 1$となります。\n\n自由度1のカイ二乗分布の確率密度関数は次のようになります。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-2_01eb68ded564938a797d039eaaa409c8'}\n\n```{.r .cell-code}\nx = c(1:2500) / 250 # 数列を作成\ny1 = dchisq(x,1) # カイ二乗分布の確率密度\n\ndf <- data.frame(x, y1) # データフレームを作成\np <- ggplot(df) + aes(x = x,y = y1) # 作図\np <- p + geom_line(size = 1) # 折れ線グラフ\np <- p + ylim(c(0,1)) + ylab(\"密度\") + xlab(\"カイ二乗値\") +\n  scale_y_continuous(expand = c(0,0), limits = c(0,1)) +\n  scale_x_continuous(expand = c(0,0), limits = c(-0.1,10))\np <- p + ggtitle(\"自由度1のχ2分布の確率密度\") +  mystyle\nprint(p)\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-2-1.png){width=1344}\n:::\n:::\n\n\n参考までに、自由度が変わると$\\chi^2$分布の形状は次のようなものになります。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-3_ba782fa084f1e7fb169c91ab1a168152'}\n\n```{.r .cell-code}\nx = c(1:2500) / 250\ny1 = dchisq(x,1) # 自由度1のカイ二乗分布の確率密度\ny3 = dchisq(x,3) # 自由度3のカイ二乗分布の確率密度\ny5 = dchisq(x,5) # 自由度5のカイ二乗分布の確率密度\n\ndf <- data.frame(x, y1, y3, y5) # データフレームを作成\ndf <- df %>%\n  pivot_longer(names_to = \"y\",values_to = \"value\",cols = -x) # データを長く整形\np <- ggplot(df) + aes(x = x,y = value, group = y, color = y) # 作図\np <- p + geom_line(size = 1) # 折れ線グラフ\np <- p + ylim(c(0,1)) + ylab(\"密度\") + xlab(\"カイ二乗値\") +\n  scale_y_continuous(expand = c(0,0), limits = c(0,1)) +\n  scale_x_continuous(expand = c(0,0), limits = c(-0.1,10))\np <- p + ggtitle(\"自由度1,3,5のχ2分布の確率密度\") +  mystyle\nprint(p)\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-3-1.png){width=1344}\n:::\n:::\n\n\n自由度1の$\\chi^2$分布における有意水準5%の値を調べるには`qchisq()`関数を使います。引数は、`p`に確率、`df`に自由度を指定します。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-4_04cc94f8dba6b290adae3624a301089a'}\n\n```{.r .cell-code}\nalpha <- 0.05  # 有意水準（ここでは5%）\ndf <- 1        # 自由度\nqchisq(1 - alpha, df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.841459\n```\n:::\n:::\n\n自由度1のカイ二乗分布における有意水準5%の値は3.84であることが分かりました。\nこの値を超えると、有意水準5%で帰無仮説を棄却することになります。\n\nでは先程計算した$\\chi^2$統計量は、有意水準5%で帰無仮説を棄却するかどうかを調べてみましょう。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-5_ba49372d00da5cc8aa59681343e27e7b'}\n\n```{.r .cell-code}\nchi2 <- 7.2\nqchisq(1 - alpha, df) < chi2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\nより、$\\chi^2$統計量は有意水準5%で帰無仮説を棄却することが分かりました。\nちなみに、自由度1のカイ二乗分布の確率密度関数と$\\chi^2$統計量の位置を重ねてみると次のようになります。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-6_731106bc3f4cde8c409c5ebf4544eeb7'}\n\n```{.r .cell-code}\ndf <- data.frame(x,y1)\np <- ggplot(df) + aes(x = x,y = y1)\np <- p + geom_line(size = 1)\np <- p + ylim(c(0,1)) + ylab(\"密度\") + xlab(\"カイ二乗値\") +\n  scale_y_continuous(expand = c(0,0), limits = c(0,1)) +\n  scale_x_continuous(expand = c(0,0), limits = c(-0.1,10))\np <- p + ggtitle(\"自由度1のχ2分布の確率密度\") +  mystyle\np <- p + geom_vline(xintercept = chi2, linetype = \"dashed\", color = \"red\")\np <- p + annotate(\"text\", x = chi2, y = 0.1, label = \"χ2 statistics\", color = \"red\")\nprint(p)\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-6-1.png){width=1344}\n:::\n:::\n\n\nこのように、$\\chi^2$統計量は、自由度1のカイ二乗分布のもとで生じる確率は、\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-7_3159ec53239fa88d1995b11b862e1902'}\n\n```{.r .cell-code}\n1 - pchisq(chi2, df = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.007290358\n```\n:::\n:::\n\n\nとなり、非常に小さな値であることが分かりました。\nつまり、2つのカテゴリー変数の間に関係がない、という帰無仮説の下で、観測された度数が発生することはほぼありえない、ということが言えるので、帰無仮説は棄却され、2つのカテゴリー変数には関係があると結論付けられます。\n\n\n### Rでχ2検定\n\nRでは`chisq.test()`関数を使ってχ2検定を行うことができます。\n引数は、`x`に度数表、`correct`に補正を行うかどうか、`p`に期待度数を指定します。\n\n先ほどの男女とメガネの例をここでも使ってみます。\nまず`matrix()`関数を使ってクロス集計表を行列として作成します。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-8_8a275da80338b5f77707d407935bc591'}\n\n```{.r .cell-code}\nO <- matrix(c(41, 81, 204, 74), nrow = 2, ncol = 2)\nrow.names(O) <- c(\"男性\", \"女性\")\ncolnames(O) <- c(\"メガネ\", \"メガネなし\")\n\nE <- matrix(c(\n  sum(O[,1])*sum(O[1,])/sum(O), #男眼鏡\n  sum(O[,1])*sum(O[2,])/sum(O), #男眼鏡無\n  sum(O[,2])*sum(O[1,])/sum(O), #女眼鏡\n  sum(O[,2])*sum(O[2,])/sum(O)  #女眼鏡無\n), nrow = 2, ncol = 2)\n\nprint(O)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     メガネ メガネなし\n男性     41        204\n女性     81         74\n```\n:::\n\n```{.r .cell-code}\nprint(E)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       [,1]    [,2]\n[1,] 74.725 170.275\n[2,] 47.275 107.725\n```\n:::\n:::\n\n\nこの観察度数と期待度数から、定義通りに$\\chi^2$統計量を計算してみます。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-9_0a9c6e391a2061836e5e54c2bc3513f8'}\n\n```{.r .cell-code}\nchi <-  (O[1,1] - E[1,1])^2 / E[1,1] + #男眼鏡\n        (O[1,2] - E[1,2])^2 / E[1,2] + #男眼鏡無\n        (O[2,1] - E[2,1])^2 / E[2,1] + #女眼鏡\n        (O[2,2] - E[2,2])^2 / E[2,2]   #女眼鏡無\nprint(chi)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 56.51731\n```\n:::\n:::\n\n\n$\\chi^2$統計量がとなりました。\nこの$\\chi^2$統計量が自由度1の$\\chi^2$分布にしたがう場合，この統計量が得られる確率は次のようになります。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-10_30d7641ddf6c8cd2e23b9f392f40d7a1'}\n\n```{.r .cell-code}\nprop <- 1 - pchisq(chi, df = 1)\nprint(prop)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.57332e-14\n```\n:::\n:::\n\n\nこの確率は`0.0000000000000055733`となり，ほぼゼロであることが分かりました。\nよって、2つのカテゴリー変数は無関係である，という帰無仮説は棄却され、2つのカテゴリー変数には関係があると結論付けられます。\n\nちなみに，上記のようなめんどくさい処理をしなくても，`R`には`chisq.test()`という関数が用意されています。\n`chisq.test()`は引数として、`x`に度数表、`correct`に補正を行うかどうか、`p`に期待度数を指定します。\n補正は行わないので，`correct`は`FALSE`とします。\n`p`はデフォルトで等確率となっているので，今回は省略します。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-11_69756743f848d1a4ed73d4b7b9febe7d'}\n\n```{.r .cell-code}\nchisq.test(O, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  O\nX-squared = 56.517, df = 1, p-value = 5.571e-14\n```\n:::\n:::\n\n\nとなり，先ほどの結果と一致しました。\n\n各マスに入る度数が少ない場合には、フィッシャーの直接確率検定を使います。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-12_821a4eb8fe078ae4bc440e86f53cb562'}\n\n```{.r .cell-code}\nfisher.test(O)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  O\np-value = 1.204e-13\nalternative hypothesis: true odds ratio is not equal to 1\n95 percent confidence interval:\n 0.1127341 0.2982245\nsample estimates:\nodds ratio \n 0.1845096 \n```\n:::\n:::\n\n\n\n### カイ二乗分布(補足)\n\nカイ二乗分布は、確率変数$Z_1, Z_2,\\dots, Z_k$が互いに独立であり、それぞれが標準正規分布$N(0,1)$に従うとき、その二乗和が従う分布を自由度$k$のカイ二乗分布といいます。\n\n$$\n\\chi^2 = Z_1^2 + Z_2^2 + \\dots + Z_k^2\n$$\n\n導出は省きますが、自由度$k$のカイ二乗分布の密度関数は、\n\n$$\n\\begin{aligned}\nf(x) =\n\\begin{cases}\n\\frac{1}{2^{k/2} \\Gamma(k/2)} x^{k/2 - 1} \\mathrm{e}^{-x/2} & (x \\geq 0)\\\\\n0 & (x < 0)\n\\end{cases}\n\\end{aligned}\n$$\n\nここで、$\\Gamma$はガンマ関数であり、\n\n$$\n\\Gamma \\left (\\frac n2 \\right) = \\int_0^{\\infty} t^{k/2 - 1} \\mathrm{e}^{-t} \\mathrm{d}t\n$$\nとなります。\n\n導出は省きますが、カイ二乗分布の期待値は$k$となり、分散は$2k$となります。\n\n## 量的変数間の関係\n\nここでは、2つ以上の量的変数間の関係を調べる方法について学びます。\n具体的には、相関係数と散布図について学習します。\n\n\n### 相関関係の種類・散布図・相関係数\n\n2つの量的変数(連続変数)が同時に変化する関係を**相関関係**(correlation)といいます。\n相関関係には、\n\n- **正の相関**(positive correlation)\n- **負の相関**(negative correlation)\n- **無相関**(no correlation)\n\nの3種類があります。\n\nまずは，2つの量的変数を使って**散布図**(scatter diagram)を描いて，目で見て相関関係があるかどうかを判断します。\nそして，**相関係数**(correlation coefficient)を計算して，数値的に相関関係があるかどうかを判断します。\n相関係数は次のように計算されます。\n\n$$\nr = \\frac{\\sum_{i=1}^n (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum_{i=1}^n (x_i - \\bar{x})^2}\\sqrt{\\sum_{i=1}^n (y_i - \\bar{y})^2}}\n$$\n\n分子は、$x$と$y$の共分散(covariance)で、分母は$x$の標準偏差と$y$の標準偏差の積です。\n相関係数$r$は$-1$から$1$の値をとります。\n$r$が$1$に近いほど正の相関が強く、$-1$に近いほど負の相関が強く、$0$に近いほど無相関になります。\n\n相関係数が$-1$から$1$の値をとることを証明することは簡単なのですが，それを書くには余白が足りないので，ここには示しません。\nコーシー・シュワルツの不等式を使うか，$x$と$y$の偏差のベクトルの角度が$\\cos$であることを示すか，のどちらかで証明できます。\n\n\n### 相関係数を使った統計的仮説検定\n\n相関係数が同じでも統計的に有意になるか否かは、標本サイズで決まるということを教科書で理解しておきましょう。\n\n### Rでやってみる {.unnumbered}\n\n母平均$0$、母標準偏差$1$の正規分布にしたがう変数$X$と$Y$を考えます。\n母集団のサイズは10000とします。\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-13_885888042e9f760958e24b9b30301a02'}\n\n```{.r .cell-code}\nN <- 10000 # 母集団のサイズ\nX <- rnorm(N, 0, 1) # 平均0，標準偏差1の正規分布からN個\nY <- rnorm(N, 0, 1) # 平均0，標準偏差1の正規分布からN個\nP <- data.frame(X,Y) # データフレームを作成\nggplot(P) + aes(X,Y) + # グラフの下地\n  geom_point() + # 散布図\n  ggtitle(\"母集団\") + mystyle # タイトルとスタイル\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-13-1.png){width=1344}\n:::\n:::\n\n\nこの母集団から標本サイズ100の標本を100個とりだし、相関係数を100個計算します。\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-14_7420e0c3aaba10070ecfe4e049e2a882'}\n\n```{.r .cell-code}\nn <- 100 # 標本サイズ\ntrial <- 100 # 試行回数\nsig <- numeric(n) # 空の入れ物\ncor <- numeric(n) # 空の入れ物\nfor(i in 1:trial){ # ループ\n  x_sample <- sample(X, n) # 母集団からn個の標本を取り出す\n  y_sample <- sample(Y, n) # 母集団からn個の標本を取り出す\n  res <- cor.test(x_sample, y_sample) # 相関係数を計算\n  sig[i] <- res$p.value # p値\n  cor[i] <- cor(x_sample, y_sample) # 相関係数\n}\ndf_cor <- data.frame(cor,sig) # p値と相関係数をデータフレームにまとめる\ndf_cor %>% arrange(sig) %>% head() # p値で並び替えて上位5つを表示\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|        cor|       sig|\n|----------:|---------:|\n|  0.3032027| 0.0021663|\n| -0.2678916| 0.0070457|\n| -0.2637771| 0.0080077|\n| -0.2509923| 0.0117747|\n|  0.2344974| 0.0188575|\n| -0.2343658| 0.0189263|\n\n</div>\n:::\n:::\n\n\nたとえば、ある標本の散布図はこうなります。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-15_1bae8d9ba21035dd99fcc9e5f14e742d'}\n\n```{.r .cell-code}\nx_sample <- sample(X, n) # 母集団Xからn個の標本を取り出す\ny_sample <- sample(Y, n) # 母集団Yからn個の標本を取り出す\ndata.frame(x_sample, y_sample) %>% # データフレームにまとめる\n    ggplot() + aes(x_sample, y_sample) + # グラフの下地\n    geom_point() + # 散布図\n    geom_smooth(method = \"lm\", se = FALSE) + # 回帰直線\n    ggtitle(\"標本\") + mystyle # タイトルとスタイル\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-15-1.png){width=1344}\n:::\n:::\n\n\n微妙に右肩上がりの関係がありそうですが、ほぼ無相関といえるでしょう。\nでは、100個の標本から計算した100個の相関係数の大きさを並べてみましょう。\n変数を並び替えるには，`dplyr`の`arrange()`関数を使います。\nデフォルトでは昇順に並び替えられますが，`arrange(desc())`とすることで降順に並び替えることができます。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-16_bfcf6461da1747e3148c328965021c15'}\n\n:::\n\n\n無相関となる母集団からの標本を100個とっているので、標本の相関係数も0に近い値となることが予想されますが、いくつかの標本では$-0.3$や$0.2$といった相関があるという結果が得られています。\n\n以下のコードで、相関係数の値が小さい順に並べています。\nggplotの`aes()`の中で、`reorder()`関数を使って、`seq_along(cor)`を`cor`の値で並び替えています。\n`reorder()`関数は第一引数の数列を第二引数の数列の値で並び替える関数です。\n`seq_along(cor)`は`1,2,3,...,100`という数列を作成し，`reorder()`関数で第一引数の数列を第二引数の数列の値で並び替えています。\n`geom_bar`の引数の中の`fill`は棒グラフの色を指定しているのですが，ここに`ifelse()`関数を使うことで，`sig`の値が`0.05`より小さい場合は赤色，そうでない場合は黒色になるようにしています。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-17_82e517c86a65d027c34625bb60607528'}\n\n```{.r .cell-code}\nggplot(data.frame(df_cor)) +\n    aes(x = reorder(seq_along(cor), cor), y = cor) +\n    geom_bar(stat = \"identity\", fill = ifelse(sig < 0.05, \"red\", \"black\")) +\n    ylab(\"相関係数\") + xlab(\"標本ID\") + ggtitle(\"相関係数の分布\") + mystyle\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-17-1.png){width=1344}\n:::\n:::\n\n\nでは、それらの値が、母集団では相関係数が$0$であるという帰無仮説が正しいとした場合に、どのくらいの確率で得られるのかを調べてみましょう。\n\n\n::: {.cell hash='presemi2023_08_cache/html/unnamed-chunk-18_bf268362d0b5c3391e47cde09e1a4235'}\n\n```{.r .cell-code}\nggplot(data.frame(df_cor)) +\n    aes(x = reorder(seq_along(sig), sig), y=sig) + # データの指定\n    geom_bar(stat=\"identity\", fill = ifelse(sig < 0.05, \"red\", \"black\")) + # 棒グラフ\n    ylab(\"p値\") + xlab(\"標本ID\") + ggtitle(\"相関係数のp値の分布\") + mystyle # 軸ラベルとタイトル\n```\n\n::: {.cell-output-display}\n![](presemi2023_08_files/figure-html/unnamed-chunk-18-1.png){width=1344}\n:::\n:::\n\n\n相関係数が0である母集団から標本を抜き出して、その標本相関係数の値が0.3となる確率$p$値は0.002となりました。\nもし自分がもっている広告費と売上高のデータから相関係数を計算し、その値が0.3であったなら、母集団では相関係数が$0$であるという帰無仮説の下では、ほとんど起こりえないことが起こったということになります。\nこの場合、帰無仮説が間違っていて、対立仮説である広告費と売上高には関係があるという仮説のほうがもっともらしい、ということになります。\n逆に、帰無仮説を棄却できなかった場合、広告費と売上高の間に**関係は無いと主張することはできません**。\n帰無仮説が棄却できなかった場合は、**関係があるかどうかはわからない**ということになります。\n\n\n### 相関関係と因果関係\n\n:::{.callout-important}\n相関関係があるからといって、必ずしも因果関係があるとは限らない。\n:::\n\n広告費と売上高の関係について考えてみましょう。\n\n\n#### 因果関係 {.unnumbered}\n\n**可能性1**：広告費が売上高に影響を与えている、という関係を想定しています。\n\n\n```{mermaid}\ngraph LR\n    A[広告費] --> B[売上高]\n```\n\n\n#### 因果関係 {.unnumbered}\n\n**可能性2**：売上高が広告費に影響を与えている、という関係を想定しています。\n\n\n\n```{mermaid}\ngraph RL\n    B[売上高] --> A[広告費]\n```\n\n\n#### 互恵関係 {.unnumbered}\n\n**可能性3** : 可能性1と可能性2が同時に起こっている、という関係を想定しています。\n\n\n```{mermaid}\ngraph LR\n    A[広告費] --> B[売上高]\n    B[売上高] --> A[広告費]\n```\n\n\n#### 見せかけの相関 {.unnumbered}\n\n広告費と売上高の両方に影響を与える第3の要因が存在する場合、広告費と売上高の間に相関関係が**あるように見える**、という想定です。\nここでは、広告費と売上高の両方に影響を与える第3の要因として、**内部資金**を想定しています。内部資金が潤沢な会社は、広告宣伝費も増加させることができるし、売上高も増加させることができる、という想定です。\n\n\n\n```{mermaid}\ngraph TB\n    A[内部資金] --> B[広告費]\n    A[内部資金] --> C[売上高]\n```\n\n```{mermaid}\ngraph TB\n    A[内部資金] --> B[広告費]\n    A --> C[売上高]\n    B -.-> C\n```\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}